function map = allo_translate(allo)
    
    % stations dictionnary
    station_names = {   ...
        'Leonardo Da Vinci',...
        'Michael Jackson',...
        'Abraham Lincoln',...
        'Martin Luther King',...
        'Isaac Newton',...
        'Albert Einstein',...
        'Mother Teresa',...
        'Walt Disney',...
        'William Shakespeare',...
        'Michelangelo',...
        'Ludwig van Beethoven',...
        'Christopher Columbus',...
        'Thomas Edison',...
        'Pablo Piccaso',...
        'Vincent Van Gogh',...
        'Benjamin Franklin',...
        'Neil Armstrong',...
        'Napoleon',...
        'George Washington',...
        'Charles Dickens',...
        'Mohammad Ali',...
        'Mozart',...
        'Princess Diana',...
        'John F. Kennedy',...
        'Elizabeth Taylor',...
        'Mark Twain',...
        'Bill Gates',...
        'Cleopatra',...
        'Stephen Hawking',...
        'Aristotle',...
        'Alexander Graham Bell',...
        'Marilyn Monroe',...
        'Gandhi',...
        'Houdini',...
        'Clint Eastwood',...
        'Alfred Hitchcock',...
        'Darth Vader',...
        'John Lennon',...
        'Michael Jordan',...
        'Tom Cruise',...
        'Elvis Presley',...
        'Plato',...
        'Thomas Jefferson',...
        'Bill Clinton',...
        'Ronald Reagan',...
        'Ernest Hemingway',...
        'Tom Hanks',...
        'Sean Connery',...
        'Dwight D. Eisenhower',...
        'Ray Charles',...
        'Magic Johnson',...
        'Denzel Washington',...
        'Bill Cosby',...
        'Pele',...
        'Harrison Ford',...
        'Beyonce',...
        'James Dean',...
        'Eddie Murphy',...
        'Meryl Streep',...
        'Dr. Seuss',...
        'George W. Bush',...
        'Sigmund Freud',...
        'Margaret Thatcher',...
        'Hillary Clinton',...
        'Mick Jagger',...
        'John Travolta',...
        'Bob Dylan',...
        'Spider Man',...
        'C. S. Lewis',...
        'Charlie Brown',...
        'Julia Roberts',...
        'Jack Nicholson',...
        'Paul Newman',...
        'Edgar Allen Poe',...
        'Jim Carrey',...
        'John F. Kennedy, Jr.',...
        'Michael J. Fox',...
        'Paul McCartney',...
        'Justin Timberlake',...
        'Robin Williams',...
        'Jane Austen',...
        'Britney Spears',...
        'Jacqueline Kennedy Onasis',...
        'Fred Astaire',...
        'Madonna',...
        'Oprah Winfrey',...
        'Whoopi Goldberg',...
        'Steve Martin',...
        'Lewis Carrol',...
        'Jesse Jackson',...
        'Helen Keller',...
        'Frank Lloyd Wright',...
        'Tyra Banks',...
        'Louis Pasteur',...
        'David Letterman',...
        'Kanye West',...
        'Vladimir Putin',...
        'Bob Hope',...
        'Lucille Ball',...
        'Carl Sagan' ...
};
                    
    station_names = station_names(randperm(length(station_names)));
    
	% map struct
    map = struct;
    
    % id
    map.id = allo.id;
    
    % nb_stations
    map.nb_stations = length(allo.main_stations);
    
    % nb_sublines
    map.nb_sublines = length(allo.main_sublines);
    
    % stations
    fprintf('allo_translate: stations\n');
    map.stations = map_createstation(nan,'',[nan,nan]);
    for i_stations = 1:map.nb_stations
        map.stations(i_stations) = map_createstation(   i_stations, ...
                                                        station_names{i_stations}, ...
                                                        allo.main_stations(i_stations).draw_position ...
                                                    );
    end
    
    % sublines
    fprintf('allo_translate: sublines\n');
    map.sublines = map_createsubline(nan,[0,0,0],nan);
    for i_sublines = 1:map.nb_sublines
        map.sublines(i_sublines) = map_createsubline(   ...
            i_sublines,...                                      % id
            allo.main_sublines(i_sublines).draw_color,...       % color
            1 ...                                               % time
                                                    );
    end
    
    % links
    fprintf('allo_translate: links\n');
    map.links = zeros(map.nb_stations,map.nb_stations);
    for i_sublines = 1:map.nb_sublines
        stops = allo.main_sublines(i_sublines).main_stations;
        for i_stops = 1:(length(stops)-1)
            map.links(stops(i_stops),stops(i_stops+1)) = i_sublines;
        end
    end
    
    % dists
    fprintf('allo_translate: distances\n');
    map.dists = map_dists(map);
    
    % avatar
    fprintf('allo_translate: avatar\n');
    map.avatar = struct();
    map.avatar.start_station = nan;
    map.avatar.start_subline = nan;
    map.avatar.in_station = nan;
    map.avatar.in_subline = nan;
    map.avatar.to_station = nan;
    map.avatar.time = nan;
    map.avatar.reward = nan;
end