function names = map_getplaces()
    names = {   ...
        'Amsterdam', ...
        'Ankara', ...
        'Argentina', ...
        'Athens', ...
        'Atlantic', ...
        'Baltimore', ...
        'Bangkok', ...
        'Beijing', ...
        'Berlin', ...
        'Bern', ...
        'Brussels', ...
        'Budapest', ...
        'Cairo', ...
        'Canberra', ...
        'Cannes', ...
        'Cape', ...
        'Chicago', ...
        'Cologne', ...
        'Copenhagen', ...
        'Delhi', ...
        'Dubai', ...
        'Dublin', ...
        'Florence', ...
        'Geneva', ...
        'Hague', ...
        'Hanoi', ...
        'Havana', ...
        'Helsinki', ...
        'Hong Kong', ...
        'Honolulu', ...
        'Istanbul', ...
        'Jakarta', ...
        'Jerusalem', ...
        'Kansas', ...
        'Kathmandu', ...
        'Kuala Lumpur', ...
        'Lisbon', ...
        'London', ...
        'Los Angeles', ...
        'Madrid', ...
        'Manila', ...
        'Melbourne', ...
        'Mexico City', ...
        'Milan', ...
        'Montreal', ...
        'Moscow', ...
        'Mumbai', ...
        'Munich', ...
        'Nazareth', ...
        'New York', ...
        'Nice', ...
        'Osaka', ...
        'Oslo', ...
        'Ottawa', ...
        'Paris', ...
        'Philadelphia', ...
        'Phnom Penh', ...
        'Prague', ...
        'Quito', ...
        'Reykjavik', ...
        'Rio de Janeiro', ...
        'Saint Petersburg', ...
        'San Francisco', ...
        'Santiago', ...
        'Sao Paulo', ...
        'Shanghai', ...
        'Singapore', ...
        'Stockholm', ...
        'Sydney', ...
        'Taipei', ...
        'Tokyo', ...
        'Toronto', ...
        'Venice', ...
        'Washington', ...
        'Zurich', ...
    };
end