function map = map_rename(map)
    
    % stations dictionnary
    station_names = {   ...
        'Ali',...
        'Armstrong',...
        'Aristotle',...
        'Astaire',...
        'Austen',...
        'Ball',...
        'Banks',...
        'Beethoven',...
        'Bell',...
        'Beyonce',...
        'Brown',...
        'Bush',...
        'Carrey',...
        'Carrol',...
        'Charles',...
        'Cleopatra',...
        'Clinton',...
        'Columbus',...
        'Connery',...
        'Cosby',...
        'Cruise',...
        'Vinci',...
        'Vader',...
        'Dean',...
        'Diana',...
        'Dickens',...
        'Disney',...
        'Dylan',...
        'Eastwood',...
        'Edison',...
        'Einstein',...
        'Eisenhower',...
        'Ford',...
        'Fox',...
        'Franklin',...
        'Freud',...
        'Gandhi',...
        'Gates',...
        'Goldberg',...
        'Hawking',...
        'Hemingway',...
        'Hitchcock',...
        'Hope',...
        'Houdini',...
        'Jackson',...
        'Jagger',...
        'Jefferson',...
        'Johnson',...
        'Jordan',...
        'Keller',...
        'Kennedy',...
        'Lennon',...
        'Letterman',...
        'Lewis',...
        'Lincoln',...
        'King',...
        'Madonna',...
        'Martin',...
        'McCartney',...
        'Michelangelo',...
        'Monroe',...
        'Mozart',...
        'Murphy',...
        'Napoleon',...
        'Newman',...
        'Newton',...
        'Nicholson',...
        'Onasis',...
        'Pasteur',...
        'Pele',...
        'Piccaso',...
        'Plato',...
        'Poe',...
        'Presley',...
        'Putin',...
        'Reagan',...
        'Roberts',...
        'Sagan',...
        'Seuss',...
        'Shakespeare',...
        'Spears',...
        'Streep',...
        'Taylor',...
        'Teresa',...
        'Thatcher',...
        'Timberlake',...
        'Travolta',...
        'Twain',...
        'Washington',...
        'Williams',...
        'Winfrey',...
        'West',...
        'Wright' ...
    };
    
    station_names = station_names(randperm(length(station_names)));
    
    % stations
    for i_stations = 1:map.nb_stations
        map.stations(i_stations).name = station_names{i_stations};
    end
    
end